/* Tablespace */
CREATE TABLESPACE SIMPLE_LEDGER_DATA
  DATAFILE 'tbs_sl' SIZE 16M AUTOEXTEND ON NEXT 16M
  MAXSIZE UNLIMITED;

/* Schema */
CREATE USER SIMPLE_LEDGER IDENTIFIED BY SIMPLE_LEDGER
  DEFAULT TABLESPACE SIMPLE_LEDGER_DATA TEMPORARY TABLESPACE TEMP;
ALTER USER SIMPLE_LEDGER ACCOUNT LOCK;
GRANT CONNECT, RESOURCE, CREATE SEQUENCE TO SIMPLE_LEDGER;
ALTER USER SIMPLE_LEDGER QUOTA UNLIMITED ON SIMPLE_LEDGER_DATA;
GRANT MERGE ANY VIEW TO SIMPLE_LEDGER;

/* Application user */
CREATE USER SIMPLE_LEDGER_APP IDENTIFIED BY SIMPLE_LEDGER DEFAULT TABLESPACE SIMPLE_LEDGER_DATA TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE, CREATE SESSION TO SIMPLE_LEDGER_APP;
ALTER USER SIMPLE_LEDGER_APP QUOTA UNLIMITED ON SIMPLE_LEDGER_DATA;
GRANT MERGE ANY VIEW TO SIMPLE_LEDGER_APP;

/* Table */
CREATE TABLE SIMPLE_LEDGER.TB_DATA(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
  , sender VARCHAR2(100) NOT NULL
  , receiver VARCHAR2(100) NOT NULL
  , amount NUMBER(38,8) NOT NULL
  , currency VARCHAR2(3) NOT NULL
  , business_time TIMESTAMP NOT NULL
) TABLESPACE SIMPLE_LEDGER_DATA;

CREATE TABLE SIMPLE_LEDGER.TB_USER(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
  , fullname VARCHAR2(100) NOT NULL
) TABLESPACE SIMPLE_LEDGER_DATA;

/* Constraints */
ALTER TABLE SIMPLE_LEDGER.TB_DATA
  ADD CONSTRAINT CHK_SENDER
  CHECK (LENGTH(sender) > 3 AND sender LIKE '% %');

ALTER TABLE SIMPLE_LEDGER.TB_DATA
  ADD CONSTRAINT CHK_RECEIVER
  CHECK (LENGTH(receiver) > 3 AND receiver LIKE '% %');

ALTER TABLE SIMPLE_LEDGER.TB_DATA
  ADD CONSTRAINT CHK_AMOUNT
  CHECK (amount > 0);

ALTER TABLE SIMPLE_LEDGER.TB_DATA
  ADD CONSTRAINT CHK_CURRENCY
  CHECK (LENGTH(currency) >= 3 AND LENGTH(currency) <= 4 AND currency = UPPER(currency));

ALTER TABLE SIMPLE_LEDGER.TB_USER
  ADD CONSTRAINT CHK_FULLNAME
  CHECK (LENGTH(fullname) > 3 AND fullname LIKE '% %');

/* Grant to access table */
GRANT SELECT, INSERT ON SIMPLE_LEDGER.TB_DATA TO SIMPLE_LEDGER_APP;
GRANT SELECT ON SIMPLE_LEDGER.TB_USER TO SIMPLE_LEDGER_APP;

/* Users */
INSERT INTO SIMPLE_LEDGER.TB_USER(fullname)
  WITH names AS (
    SELECT 'Demarcus Dibernardo' AS fullname FROM dual UNION ALL
    SELECT 'Kiesha Kua' FROM dual UNION ALL
    SELECT 'Nydia Newlon' FROM dual UNION ALL
    SELECT 'Ava Aquino' FROM dual UNION ALL
    SELECT 'Lauryn Lachowicz' FROM dual UNION ALL
    SELECT 'Shoshana Shackelford' FROM dual UNION ALL
    SELECT 'Velma Vawter' FROM dual UNION ALL
    SELECT 'Katina Korte' FROM dual UNION ALL
    SELECT 'Kacy Kruger' FROM dual UNION ALL
    SELECT 'Tosha Turmelle' FROM dual UNION ALL
    SELECT 'Catrice Corder' FROM dual UNION ALL
    SELECT 'Eliseo Eccles' FROM dual UNION ALL
    SELECT 'Carlena Coakley' FROM dual UNION ALL
    SELECT 'Mallory Mcculler' FROM dual UNION ALL
    SELECT 'Marilynn Manz' FROM dual UNION ALL
    SELECT 'Gita Guo' FROM dual UNION ALL
    SELECT 'Alfredia Arebalo' FROM dual UNION ALL
    SELECT 'Liane Laguardia' FROM dual UNION ALL
    SELECT 'Russell Rochell' FROM dual UNION ALL
    SELECT 'Peter Perlmutter' FROM dual UNION ALL
    SELECT 'Alita Abron' FROM dual UNION ALL
    SELECT 'Adah Ausmus' FROM dual UNION ALL
    SELECT 'Mitchell Mattingly' FROM dual UNION ALL
    SELECT 'Tonette Toews' FROM dual UNION ALL
    SELECT 'Brett Batt' FROM dual UNION ALL
    SELECT 'Eugenia Eisenstein' FROM dual UNION ALL
    SELECT 'Tiffanie Tackitt' FROM dual UNION ALL
    SELECT 'Minh Marsala' FROM dual UNION ALL
    SELECT 'Vaughn Vida' FROM dual UNION ALL
    SELECT 'Terica Toms' FROM dual UNION ALL
    SELECT 'Juana Jeremiah' FROM dual UNION ALL
    SELECT 'Katherine Keefer' FROM dual UNION ALL
    SELECT 'Myesha Macek' FROM dual UNION ALL
    SELECT 'Bette Bribiesca' FROM dual UNION ALL
    SELECT 'Dionne Durrett' FROM dual UNION ALL
    SELECT 'Arvilla Almquist' FROM dual UNION ALL
    SELECT 'Laci Lawver' FROM dual UNION ALL
    SELECT 'Kip Kearney' FROM dual UNION ALL
    SELECT 'Raguel Rising' FROM dual UNION ALL
    SELECT 'Rich Ryland' FROM dual UNION ALL
    SELECT 'Charis Claflin' FROM dual UNION ALL
    SELECT 'Shaquita Soliz' FROM dual UNION ALL
    SELECT 'Zula Zwick' FROM dual UNION ALL
    SELECT 'Bill Bachmann' FROM dual UNION ALL
    SELECT 'Jack Jeppesen' FROM dual UNION ALL
    SELECT 'Lula Locicero' FROM dual UNION ALL
    SELECT 'Christena Clausing' FROM dual UNION ALL
    SELECT 'Estella Edenfield' FROM dual UNION ALL
    SELECT 'Roseanna Rosa' FROM dual UNION ALL
    SELECT 'Cassaundra Colclough' FROM dual
  )
  SELECT fullname FROM names;

COMMIT;