/* Tablespace */
CREATE TABLESPACE SIMPLE_LEDGER_DATA
  DATAFILE 'tbs_sl' SIZE 16M AUTOEXTEND ON NEXT 16M
  MAXSIZE UNLIMITED;

/* Schema */
CREATE USER SIMPLE_LEDGER IDENTIFIED BY SIMPLE_LEDGER
  DEFAULT TABLESPACE SIMPLE_LEDGER_DATA TEMPORARY TABLESPACE TEMP;
ALTER USER SIMPLE_LEDGER ACCOUNT LOCK;
GRANT CONNECT, RESOURCE, CREATE SEQUENCE TO SIMPLE_LEDGER;
ALTER USER SIMPLE_LEDGER QUOTA UNLIMITED ON SIMPLE_LEDGER_DATA;
GRANT MERGE ANY VIEW TO SIMPLE_LEDGER;

/* Application user */
CREATE USER SIMPLE_LEDGER_APP IDENTIFIED BY SIMPLE_LEDGER DEFAULT TABLESPACE SIMPLE_LEDGER_DATA TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE, CREATE SESSION TO SIMPLE_LEDGER_APP;
ALTER USER SIMPLE_LEDGER_APP QUOTA UNLIMITED ON SIMPLE_LEDGER_DATA;
GRANT MERGE ANY VIEW TO SIMPLE_LEDGER_APP;

/* Table */
CREATE TABLE SIMPLE_LEDGER.TB_DATA(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
  , sender VARCHAR2(100) NOT NULL
  , receiver VARCHAR2(100) NOT NULL
  , currency VARCHAR2(3) NOT NULL
  , date_ts TIMESTAMP NOT NULL
) TABLESPACE SIMPLE_LEDGER_DATA;

/* Constraints */
ALTER TABLE SIMPLE_LEDGER.TB_DATA
  ADD CONSTRAINT CHK_SENDER
  CHECK (LENGTH(sender) > 3 AND sender LIKE '% %');

ALTER TABLE SIMPLE_LEDGER.TB_DATA
  ADD CONSTRAINT CHK_RECEIVER
  CHECK (LENGTH(receiver) > 3 AND receiver LIKE '% %');

ALTER TABLE SIMPLE_LEDGER.TB_DATA
  ADD CONSTRAINT CHK_CURRENCY
  CHECK (LENGTH(currency) >= 3 AND LENGTH(currency) <= 4 AND currency = UPPER(currency));

/* Grant to access table */
GRANT SELECT, INSERT ON SIMPLE_LEDGER.TB_DATA TO SIMPLE_LEDGER_APP;